version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 999999999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - zookeeper

  app:
    build: .
    volumes:
      - ./server:/application
      - app-python-site-packages:/usr/local/lib/python3.6/site-packages
      - app-usr-local-bin:/usr/local/bin
      - worker-data:/data/
    ports:
      - "6066:6066"
      - "6067:6067"
      - "6068:6068"
      - "6069:6069"
    depends_on:
      - kafka
    env_file:
      - ./.env


volumes:
  redis_data:
    driver: local

  app-python-site-packages:
    driver: local

  app-usr-local-bin:
    driver: local

  worker-data:
    driver: local
